config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"

    devise_for :users

    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

    patch "/notifications/mark_all_as_read", to: "markallasread#update", as: "mark_all_as_read"

    namespace :accountant do
      resources :incomes, only: %i(index new create)
      resources :suppliers, except: %i(show destroy)
      resources :requests, only: %i(index update show)
    end

    namespace :admin do
      resources :users, only: %i(new create)
    end

    namespace :manager do
      resources :requests, only: %i(show update index)
    end

    namespace :accountmanager do
      resources :suppliers, except: %i(show destroy)
    end

    resources :requests, except: :destroy

    resources :notifications, only: %i(update index)

    mount ActionCable.server => "/cable"
    mount Sidekiq::Web => "/sidekiq"
    mount Api => "/"
  end
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user
  belongs_to :item, polymorphic: true

  after_create{NotificationBroadcastJob.perform_now(self)}

  scope :lastest, ->{order created_at: :desc}
  scope :unviewed, ->{where viewed: false}
  scope :notification_user, ->(user_id){where user_id: user_id}
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :get_notification_by_id, only: :update

  def index
    @notifications = Notification.notification_user(current_user.id).lastest
    render json: {html: render_to_string(partial: "notifications", locals: {notifications: @notifications})}
  end

  def update
    if @notification.update viewed: true
      if current_user.manager?
        redirect_to manager_request_path @notification.item
      else
        redirect_to request_path @notification.item
      end
    else
      redirect_to root_url
    end
  end

  private

  def get_notification_by_id
    @notification = Notification.find_by id: params[:id]
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
  # rubocop:disable Rails/OutputSafety
  def render_notifications notifications
    if notifications.blank?
      render "notifications/notification_empty"
    else
      notifications.map do |notification|
        render "notifications/notification", notification: notification
      end.join("").html_safe
    end
  end
  # rubocop:enable Rails/OutputSafety
end

app/views/notifications/_notification.html.erb
<%= link_to notification_path(notification), remote: true, method: :patch, class: "dropdown-item" do %>
  <div class="d-flex">
    <div>
      <i class="fas fa-envelope"></i>
    </div>
    <div class="ml-3 text-notify">
      <div>
        <span class="text-sm">
          <% if current_user.manager? && notification.item.user_id != current_user.id %>
            <%= t ".notify_for_manager_msg" %> <%= notification.item.user.name %>
          <% elsif current_user.accountant? && notification.item.user_id != current_user.id %>
            <%= t ".notify_for_manager_msg" %> <%= notification.item.user.name %>
          <% else %>
            <%= t ".notify_msg" %> <%= t ".#{notification.item.status}" %>
          <% end %>
        </span>
      </div>
      <div class="text-sm <%= notification.viewed ? "text-muted" : "unread-noti" %>">
        <span>
          <%= time_ago_in_words notification.item.updated_at %> <%= t ".ago" %>
        </span>
      </div>
    </div>
    <% unless notification.viewed %>
      <div class="d-flex align-items-center">
        <i class="fas fa-circle fa-xs unread-noti"></i>
      </div>
    <% end %>
  </div>
<% end %>
<div class="dropdown-divider"></div>

app/views/notifications/_notification_empty.html.erb
<span class="dropdown-item text-center">
  <%= t ".empty_notification" %>
</span>

app/views/notifications/_notifications.html.erb
<%= render_notifications notifications %>

app/views/notifications/index.js.erb
$("#notification-content").html("<%= j (render_notifications @notifications) %>")