config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"

    devise_for :users

    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

    patch "/notifications/mark_all_as_read", to: "markallasread#update", as: "mark_all_as_read"

    namespace :accountant do
      resources :incomes, only: %i(index new create)
      resources :suppliers, except: %i(show destroy)
      resources :requests, only: %i(index update show)
    end

    namespace :admin do
      resources :users, only: %i(new create)
    end

    namespace :manager do
      resources :requests, only: %i(show update index)
    end

    namespace :accountmanager do
      resources :suppliers, except: %i(show destroy)
    end

    resources :requests, except: :destroy

    resources :notifications, only: %i(update index)

    mount ActionCable.server => "/cable"
    mount Sidekiq::Web => "/sidekiq"
    mount Api => "/"
  end
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= pluralize object.errors.count, t(".error") %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_toaster.html.erb
<% unless flash.empty? %>
  <script type="text/javascript">
    <% flash.each do |f| %>
      <% type = f[0].to_s.gsub("alert", "error").gsub("notice", "info") %>
      toastr["<%= type %>"]("<%= f[1] %>", "", {
        "positionClass": "toast-top-right",
        "showDuration": "300",
        "hideDuration": "1000",
        "timeOut": "6000",
        "extendedTimeOut": "3000"
      })
    <% end %>
  </script>
<% end %>

app/views/shared/_request_detail.html.erb
<div class="card">
  <div class="card-header" id="card-header-request">
    <h2 class="card-title text-center col-12 font-weight-bold" id="card-title-request">
      <%= t ".request_detail" %>
    </h2>
  </div>
  <div class="card-body" id="card-body-request">
    <div class="row request-row">
      <div class="col-3">
        <div class="font-weight-bold">
          <%= t ".requestor" %>
        </div>
      </div>
      <div class="col-9">
        <%= request.user_name %>
      </div>
    </div>
    <div class="row request-row">
      <div class="col-3">
        <div class="font-weight-bold">
          <%= t ".title" %>
        </div>
      </div>
      <div class="col-9">
        <%= request.title %>
      </div>
    </div>
    <div class="row request-row">
      <div class="col-3">
        <div class="font-weight-bold">
          <%= t ".content" %>
        </div>
      </div>
      <div class="col-9">
        <%= request.content %>
      </div>
    </div>
    <div class="row request-row">
      <div class="col-3">
        <div class="font-weight-bold">
          <%= t ".status" %>
        </div>
      </div>
      <div class="col-9" id="req_status_name">
        <small class="badge badge-<%= modify_label_color request.status.parameterize.underscore.to_sym %>"
          style="text-decoration: <%= request.status == "canceled"? "line-through" : "none" %>;">
          <%= t ".#{request.status}" %>
        </small>
      </div>
    </div>
    <% if request.reason.present? %>
      <div class="row request-row">
        <div class="col-3">
          <div class="font-weight-bold">
            <%= t ".reason" %>
          </div>
        </div>
        <div class="col-9">
          <%= request.reason %>
        </div>
      </div>
    <% end %>
    <div class="row request-row">
      <div class="col-3">
        <div class="font-weight-bold">
          <%= t ".sum" %>
        </div>
      </div>
      <div class="col-9">
        <%= number_to_currency sum_amount(request).values[0], unit: "" %>
      </div>
    </div>
    <div class="row request-row">
      <div class="col-3">
        <div class="font-weight-bold">
          <%= t ".currency" %>
        </div>
      </div>
      <div class="col-9">
        <%= request.currency %>
      </div>
    </div>
    <div class="request-details">
      <h3 class="text-center mt-4 mb-3">
        <%= t ".details" %>
      </h3>
      <table class="table table-hover table-bordered table-striped">
        <thead lass="text-nowrap">
          <tr>
            <th class="text-center">
              <label for="department">
                <%= t ".section" %>
              </label>
            </th>
            <th class="text-center">
              <label for="description">
                <%= t ".des" %>
              </label>
            </th>
            <th class="text-center">
              <label for="money_amount">
                <%= t ".amount" %>
              </label>
            </th>
          </tr>
        </thead>
        <tbody>
          <% request.request_details.each do |req| %>
            <tr>
              <td>
                <%= req.section_name %>
              </td>
              <td>
                <%= req.description %>
              </td>
              <td>
                <%= number_to_currency req.amount, unit: currency_symbol(request.currency) %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <div class="card-footer">
    <div class="row request-row">
      <div class="col-6">
        <div class="mr-auto">
          <% if check_requests %>
            <%= link_to t(".go_back"), manager_requests_path, class: "btn btn-primary" %>
          <% elsif current_user.accountant? %>
            <%= link_to t(".go_back"), accountant_requests_path, class: "btn btn-primary" %>
          <% else %>
            <%= link_to t(".go_back"), requests_path, class: "btn btn-primary" %>
          <% end %>
        </div>
      </div>
      <div class="col-6">
        <div class="float-right inline">
          <% if check_requests && request.pending? %>
            <%= link_to  "#", class: "btn btn-danger mr-2", id: "reject_btn", data: {toggle: "modal", target: "#rejectConfirmModal"} do %>
              <%= t ".reject" %>
            <% end %>

            <!-- Modal -->
            <%= render "shared/modal/reject_modal", role: :manager, request: request %>
            <%= link_to "#", class: "btn btn-success mr-2", id: "approve_btn", data: {toggle: "modal", target: "#approveConfirmModal"} do %>
              <%= t ".approve" %>
            <% end %>

            <!-- Modal -->
            <%= render "shared/modal/approve_modal", manager: :manager, request: request %>
          <% end %>
          <% if !check_requests && (request.pending? || request.approved? && current_user.manager?) %>
            <%= link_to "#", class: "btn btn-secondary mr-2", id: "cancel_btn", data: {toggle: "modal", target: "#cancelConfirmModal"} do %>
              <%= t ".cancel" %>
            <% end %>
            <%= render "shared/modal/cancel_modal", status_canceled: true %>
            <%= link_to t(".edit"), edit_request_path(request), id: "edit_btn", class: "btn btn-primary mr-2" %>
          <% end %>
          <% if current_user.accountant? && request.approved? %>
            <%= link_to  "#", class: "btn btn-danger mr-2", id: "reject_btn", data: {toggle: "modal", target: "#rejectConfirmModal"} do %>
              <%= t ".reject" %>
            <% end %>
            <%= render "shared/modal/reject_modal", role: :accountant, request: request %>
            <%= link_to  "#", class: "btn btn-warning mr-2 text-white", id: "paid_btn", data: {toggle: "modal", target: "#paidConfirmModal"} do %>
              <%= t ".paid" %>
            <% end %>
            <%= render "shared/modal/paid_modal", role: :accountant, request: request %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="d-none">
    <small id='paid-label' class='badge badge-warning' style='text-decoration: none;'><%= t ".paid" %></small>
    <small id='reject-label' class='badge badge-danger' style='text-decoration: none;'><%= t ".rejected" %></small>
    <small id='approve-label' class='badge badge-success' style='text-decoration: none;'><%= t ".approved" %></small>
    <small id='canceled-label' class='badge badge-dark' style='text-decoration: line-through;'><%= t ".canceled" %></small>
  </div>
</div>

app/views/shared/_request_list.html.erb
<% provide :title, t(".head") %>
<% unless section_requests %>
  <div class="header">
    <%= link_to new_request_path, class: "btn btn-success", data: {turbolinks: false} do %>
      <i class="fa fa-plus"></i> <%= t ".new_request" %>
    <% end %>
  </div>
<% end %>
<div class="card">
  <div class="card-body" id="form-request">
    <h2 class="card-title-custom text-center w-100">
      <%= t ".head" %>
    </h2>
  </div>
  <%= render "shared/request_search_form", search_request: search_request, path: path%>
  <% if requests.present? %>
     <table class="table table-striped table-hover table-bordered padding-margin-0">
        <thead>
          <tr>
            <th class="text-center" scope="col"><%= t ".requestor" %></th>
            <th class="text-center" scope="col"><%= t ".title" %></th>
            <th class="text-center" scope="col"><%= t ".created_at" %></th>
            <th class="text-center" scope="col"><%= t ".amount" %></th>
            <th class="text-center" scope="col"><%= t ".status" %></th>
            <th class="text-center" scope="col"><%= t ".actions" %></th>
            <th class="text-center" scope="col"><%= t ".history" %></th>
          </tr>
        </thead>
        <tbody>
          <% requests.each_with_index do |request, index| %>
          <tr>
            <td><%= request.user_name %></td>
            <td><%= request.title %></td>
            <td><%= I18n.localize request.created_at, format: t("app.dates.format") %></td>
            <td> <%=number_to_currency sum_amount(request).values[0], unit: currency_symbol(request.currency)%></td>
            <td>
              <small class="badge badge-<%= modify_label_color request.status.parameterize.underscore.to_sym %>"
                style="text-decoration: <%= request.status=="canceled"? "line-through" : "none" %>;">
                <%= t ".#{request.status}" %>
              </small>
            </td>
            <td>
              <% if section_requests %>
                <%= link_to manager_request_path(request), class: "btn btn-info btn-sm", data: {toggle: "tooltip", placement: "top"}, title: t(".detail") do %>
                  <i class="fa fa-eye"></i>
                <% end %>
              <% elsif accountant_requests %>
                <%= link_to accountant_request_path(request), class: "btn btn-info btn-sm", data: {toggle: "tooltip", placement: "top"}, title: t(".detail") do %>
                  <i class="fa fa-eye"></i>
                <% end %>
              <% else %>
                <% if request.pending? || request.approved? && current_user.manager? %>
                  <%= link_to edit_request_path(request), class: "btn btn-danger btn-sm", data: {toggle: "tooltip", placement: "top"}, title: t(".edit") do %>
                    <i class="fa fa-edit"></i>
                  <% end %>
                <% end %>
                <%= link_to request_path(request), class: "btn btn-info btn-sm", data: {toggle: "tooltip", placement: "top"}, title: t(".detail") do %>
                  <i class="fa fa-eye"></i>
                <% end %>
              <% end %>
            </td>
            <td>
              <% if request.paid? %>
                <%= link_to "#", class: "btn btn-primary btn-sm", data: {toggle: "modal", target: "#historyModal#{request.id}"}, title: t(".detail") do %>
                  <i class="fa fa-eye"></i>
                <% end %>
                <%= render "shared/modal/history_modal", history: request.history, request: request %>
              <% else %>
              <% end %>
            </td>
          </tr>
          <% end %>
        </tbody>
    </table>
  <% else %>
    <div class="text-center empty-results"><%= t ".no_results" %></div>
  <% end %>
  <div class="card-footer clearfix">
    <ul class="pagination pagination-sm m-0 float-right">
      <%= paginate requests, theme: "twitter-bootstrap-4" %>
    </ul>
  </div>
</div>

app/views/shared/_request_search_form.html.erb
<%= search_form_for search_request, {url: path} do |f| %>
  <div class="d-flex justify-content-between mb-3">
    <div class="col-5">
    <% if path == manager_requests_path || path == accountant_requests_path %>
      <div class="form-group d-flex">
        <div class="input-group">
          <%= f.search_field :user_name_cont, class: "form-control", placeholder: "#{I18n.t "placeholder.requestor"}" %>
        </div>
        <div class="input-group-append" data-toggle="tooltip" data-placement="top" title='<%= t "tooltip.requestor" %>'>
          <span class="input-group-text-custom">
            <i class="fas fa-user fa-sm"></i>
          </span>
        </div>
      </div>
    <% end %>
      <div class="form-group d-flex">
        <div class="input-group">
          <%= f.select :request_details_section_name_eq, options_from_collection_for_select(Section.all, :name, :name_initial, search_request.request_details_section_name_eq), {prompt: "#{I18n.t "prompt.any_section"}"}, {class: "form-control"} %>
        </div>
        <div class="input-group-append" data-toggle="tooltip" data-placement="top" title='<%= t "tooltip.section" %>'>
          <span class="input-group-text-custom">
            <i class="fas fa-building fa-sm"></i>
          </span>
        </div>
      </div>
      <div class="form-group d-flex">
        <div class="input-group">
        <select class="form-control" name="q[status_eq]" id="q_status_eq">
          <option value=""><%= t "prompt.any_status" %></option>
          <% Request.statuses.each do |value, key| %>
            <option value="<%= key %>%" <%= search_request.status_eq == key ? "selected" : "" %>><%= t "status.#{value}" %></option>
          <% end %>
        </select>
        </div>
        <div class="input-group-append" data-toggle="tooltip" data-placement="top" title='<%= t "tooltip.status" %>'>
          <span class="input-group-text-custom">
            <i class="fas fa-comment-dots fa-sm"></i>
          </span>
        </div>
      </div>
    </div>
    <div class="col-5">
      <div class="form-group d-flex">
        <div class="input-group">
          <%= f.search_field :title_or_content_or_request_details_description_cont, class: "form-control", placeholder: "#{I18n.t "placeholder.title_cont_des"}" %>
        </div>
        <div class="input-group-append" data-toggle="tooltip" data-placement="top" title='<%= t "tooltip.title_cont_des" %>'>
          <span class="input-group-text-custom">
            <i class="fas fa-file-alt fa-sm"></i>
          </span>
        </div>
      </div>

      <div class="form-group d-flex">
        <div class="input-group">
          <%= f.date_field :created_at_eq, class: "form-control input-sm date-picker", data: {provide: "datepicker"}, defaultvalue: "" %>
        </div>
      </div>
      <div class="form-group d-flex justify-content-between">
        <%= f.number_field :sum_amount_gteq, step: 0.01, min: 0, class: "form-control col-5", placeholder: "#{I18n.t "placeholder.minimum_money_amount"}" %>
        <%= f.number_field :sum_amount_lteq, step: 0.01, min: 0, class: "form-control col-5", placeholder: "#{I18n.t "placeholder.maximum_money_amount"}" %>
      </div>

      <div class="d-flex">
        <%= button_tag(class: "btn btn-primary col-4") do %>
          <i class="far fa-check-circle"></i>
          <%= t "search_form.search" %>
        <% end %>
        <button id="clear-condition-search" class="btn btn-secondary col-4 ml-3" type="button">
          <i class="far fa-trash-alt mr-2"></i>
          <%= t "search_form.clear" %>
        </button>
      </div>
    </div>
  </div>
<% end %>