config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"

    devise_for :users

    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

    patch "/notifications/mark_all_as_read", to: "markallasread#update", as: "mark_all_as_read"

    namespace :accountant do
      resources :incomes, only: %i(index new create)
      resources :suppliers, except: %i(show destroy)
      resources :requests, only: %i(index update show)
    end

    namespace :admin do
      resources :users, only: %i(new create)
    end

    namespace :manager do
      resources :requests, only: %i(show update index)
    end

    namespace :accountmanager do
      resources :suppliers, except: %i(show destroy)
    end

    resources :requests, except: :destroy

    resources :notifications, only: %i(update index)

    mount ActionCable.server => "/cable"
    mount Sidekiq::Web => "/sidekiq"
    mount Api => "/"
  end
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  SUPPLIERS_PARAMS = %i(name taxNum address sup_type).freeze
  VALID_TAX_NUMBER_REGEX = Settings.validations.supplier.tax_regex

  enum sup_type: {personal: true, organization: false}

  belongs_to :user

  has_many :incomes, dependent: :destroy

  delegate :name, to: :user, prefix: true

  validates :name, presence: true,
                   uniqueness: {case_sensitive: false}
  validates :taxNum, presence: true,
                     format: {with: VALID_TAX_NUMBER_REGEX, message: I18n.t("accountant.suppliers.message_err")},
                     uniqueness: {case_sensitive: false}
  validates :address, presence: true
  validates :sup_type, presence: true, inclusion: {in: sup_types.keys}

  scope :own_supplier, ->(user_id){where user_id: user_id}
  scope :sort_by_name, ->{order name: :asc}
  scope :sort_by_created_at, ->{order created_at: :desc}
end

app/controllers/accountant/suppliers_controller.rb
class Accountant::SuppliersController < Accountant::ApplicationController
  include SupplierAction

  def index
    @suppliers = Supplier.sort_by_created_at.page(params[:page]).per Settings.pagination.items_per_pages
    @page = params[:page].nil? ? Settings.pagination.default_page : params[:page].to_i
  end

  def new
    @supplier = Supplier.new
  end

  def create
    @supplier = Supplier.new supplier_params.merge user_id: current_user.id
    if @supplier.save
      flash[:success] = t ".success_mess"
      redirect_to accountant_suppliers_path
    else
      flash[:error] = t ".fail_mess_create"
      render :new
    end
  end

  def edit; end

  def update
    if @supplier.update supplier_params
      flash[:success] = t ".success_mess"
      redirect_to accountant_suppliers_path
    else
      flash[:error] = t ".fail_mess"
      render :edit
    end
  end

  private

  def supplier_params
    params.require(:supplier).permit Supplier::SUPPLIERS_PARAMS
  end
end

app/controllers/accountmanager/application_controller.rb
class Accountmanager::ApplicationController < ApplicationController
  before_action :require_accountant_manager

  def home; end

  private

  def require_accountant_manager
    return if current_user.accountmanager?

    redirect_to root_path, flash: {error: t(".required_accountant_manager")}
  end
end

app/controllers/accountmanager/suppliers_controller.rb
class Accountmanager::SuppliersController < Accountmanager::ApplicationController
  include SupplierAction

  def index
    @suppliers = Supplier.sort_by_created_at.page(params[:page]).per Settings.pagination.items_per_pages
    @page = params[:page].nil? ? Settings.pagination.default_page : params[:page].to_i
  end

  def new
    @supplier = Supplier.new
  end

  def create
    @supplier = Supplier.new supplier_params.merge user_id: current_user.id
    if @supplier.save
      flash[:success] = t ".success_mess"
      redirect_to accountmanager_suppliers_path
    else
      flash[:error] = t ".fail_mess_create"
      render :new
    end
  end

  def edit; end

  def update
    params = supplier_params
    if params[:sup_type].present? && @supplier.update(params)
      flash[:success] = t ".success_mess"
      redirect_to accountmanager_suppliers_path
    else
      flash[:error] = t ".fail_mess"
      render :edit
    end
  end

  private

  def supplier_params
    params.require(:supplier).permit Supplier::SUPPLIERS_PARAMS
  end
end

app/controllers/concerns/supplier_action.rb
module SupplierAction
  extend ActiveSupport::Concern

  included do
    before_action :able_to_update_supplier, only: %i(update edit)
  end

  def edit; end

  def update; end

  private

  def able_to_update_supplier
    @supplier = if current_user.accountmanager?
                  Supplier.find_by id: params[:id]
                elsif current_user.accountant?
                  able_to_update_supplier_for_accountant
                end

    return if @supplier.present?

    flash[:error] = t "shared.sup_not_found"
    redirect_to root_url
  end

  def able_to_update_supplier_for_accountant
    supplier = Supplier.find_by id: params[:id]
    accountant_suppliers = Supplier.own_supplier current_user.id
    accountant_suppliers.include?(supplier) ? supplier : nil
  end
end

app/views/accountmanager/suppliers/_form.html.erb
<%= form_for [:accountmanager, supplier], class: "form" do |f| %>
  <div class="card-body">
    <div>
      <div class="form-group">
        <%= f.label :name, t(".name"), class: "my-require" %>
        <%= f.text_field :name, class: "form-control", maxlength: "60", required: true %>
        <div class="invalid-feedback d-block">
          <%= f.object.errors.full_messages_for(:name).join("\n") %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :taxNum, t(".taxNum"), class: "my-require" %>
        <%= f.text_field :taxNum, class: "form-control", maxlength: "14", required: true %>
        <div class="invalid-feedback d-block">
          <%= f.object.errors.full_messages_for(:taxNum).join("\n") %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :address, t(".address"), class: "my-require"%>
        <%= f.text_area :address, class: "form-control", maxlength: "140", required: true %>
        <div class="invalid-feedback d-block">
          <%= f.object.errors.full_messages_for(:address).join("\n") %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :sup_type, t(".sup_type"), class: "my-require"%>
        <div class="col-5">
          <div class="form-check">
            <%= f.radio_button(:sup_type, "personal", class: "form-check-input", checked: params[:sup_type] = supplier.personal?)%>
            <label class="checkbox"><%= t(".personal") %></label>
          </div>
          <div class="form-check">
            <input class="form-check-input" type="radio" name="exampleRadios" id="exampleRadios2" value="option2">
            <%= f.radio_button(:sup_type, "organization", class: "form-check-input", checked: params[:sup_type] = supplier.organization?) %>
            <label class="checkbox"><%= t(".organization") %></label>
          </div>
        </div>
        <div class="invalid-feedback d-block">
          <%= f.object.errors.full_messages_for(:sup_type).join("\n") %>
        </div>
      </div>
      <div class="row">
        <div class="col-10"></div>
        <div class="col-2">
          <%= f.submit yield(:button_text), class: "btn btn-primary" %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/accountmanager/suppliers/edit.html.erb
<% provide :title, t(".title") %>
<% provide :button_text, t(".button") %>
<div class="card">
  <div>
    <h2 class="card-title-custom text-center w-100">
      <%= t ".heading" %>
    </h2>
  </div>
  <%= render "form", supplier: @supplier %>
</div>

app/views/accountmanager/suppliers/index.html.erb
<% provide :title, t(".title") %>
<div class="header">
  <%= link_to new_accountmanager_supplier_path, class: "btn btn-success", data: {turbolinks: false} do %>
    <i class="fa fa-plus"></i> <%= t(".new_supplier") %>
  <% end %>
</div>
<div class="card card-primary">
  <div>
    <h2 class="card-title-custom text-center w-100">
      <%= t ".heading" %>
    </h2>
  </div>
  <div class="card-body">
    <table class="table table-bordered table-striped">
      <thead class="text-nowrap">
        <tr>
          <th><%= t ".num" %></th>
          <th><%= t ".name" %></th>
          <th><%= t ".taxNum" %></th>
          <th><%= t ".address" %></th>
          <th><%= t ".sup_type" %></th>
          <th><%= t ".created_by" %></th>
          <th><%= t ".actions" %></th>
        </tr>
      </thead>
      <tbody>
      <% @suppliers.each_with_index do |supplier, index| %>
        <tr>
          <td><%= index + 1 + (@page-1)*Settings.pagination.items_per_pages %></td>
          <td><%= supplier.name %></td>
          <td><%= supplier.taxNum %></td>
          <td><%= supplier.address %></td>
          <td>
            <span class="text-<%= supplier.personal? ? "primary" : "danger" %>">
              <%= t ".#{supplier.sup_type}" %>
            </span>
          </td>
          <td><%= supplier.user_name %></td>
          <td class="text-nowrap text-center">
            <%= link_to edit_accountmanager_supplier_path(supplier), class: "btn btn-danger btn-sm", data: {toggle: "tooltip", placement: "top"}, title: t(".edit") do %>
              <i class="fa fa-edit"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
  <!-- /.card-body -->
  <div class="card-footer clearfix">
    <ul class="pagination pagination-sm m-0 float-right">
      <%= paginate @suppliers, theme: "twitter-bootstrap-4" %>
    </ul>
  </div>
</div>

app/views/accountmanager/suppliers/new.html.erb
<% provide :title, t(".title") %>
<% provide :button_text, t(".button") %>
<div class="card">
  <div>
    <h2 class="card-title-custom text-center w-100">
      <%= t ".heading" %>
    </h2>
  </div>
  <%= render "form", supplier: @supplier %>
</div>